#
# Copyright 2018 Yahoo Japan Corporation.
# Licensed under the terms of the MIT license.
# See LICENSE in the project root.
#
version: "2"

services:
  zk:
    image: zookeeper:3.4.11
    container_name: zk
    hostname: zk
    privileged: true
    networks:
          solr-nw:
  solr:
    image: solr:7.2.1
    command: solr-foreground -cloud -z zk:2181
    container_name: solr
    hostname: solr
    privileged: true
    depends_on:
      - zk
    volumes:
      - ./sample-apps:/solr-sample-apps
    ports:
      - 8983:8983
    networks:
      solr-nw:

networks:
  solr-nw: